domain_path: /1work/fpgaproc/driver_for_both_ips/only_i2c/export/only_i2c/sw/standalone_microblaze_0
app_src_dir: /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
